# Site settings
title: "Firice's blog"
email: firiceguo@gmail.com
description: "Firice's blog"
baseurl: ""
url: "https://firiceguo.github.io"
title_description: "This is a personal blog to record my thinking.
I would try my best to keep both me and my blog progressing.
If you have some questions or suggestions, please feel free to contact me via email (firiceguo@gmail.com)."
title_image: "https://firiceguo.github.io/images/title.png"
google_analytics: "UA-73945224-1"
disqus_account: firiceguo
github_repository: https://github.com/firiceguo/firiceguo.github.io
addthis_id: ra-57dcea0e3c2d5f49
post_limit: 10

# Social usernames/URLs
twitter_username: 
github_username:  firiceguo
linkedin_link: 
google_plus_link: 
stackoverflow_link: 


gems: ["jemoji"]

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://github.com/jekyll/jekyll\">jekyll</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/firiceguo/firiceguo.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
