#
###################################
# Site wide configuration
####################################
#
title: Firice
email: firiceguo@gmail.com
description: "My Place && Palace."
url: https://firiceguo.github.io


#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Shanghai
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Firice
  avatar: logo.png
  job: "To create is to live."
  bio: "Follow your dream && Fake your death."
  email: firiceguo@gmail.com
  disqus-shortname: firiceguo
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: "UA-73945224-1"
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: firiceguo
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: u/3982925747
  flickr: #username
  500px: #username
  codepen: #username

gems:
  - jemoji
